[package]
name = "mca"
description = "Reader/Writer for Minecraft Region Files (.mca)"
version = "2.1.2"
edition = "2024"
license = "MIT"
authors = ["VilleOlof"]
readme = "readme.md"
repository = "https://github.com/VilleOlof/mca"
homepage = "https://github.com/VilleOlof/mca"
keywords = ["minecraft", "region", "mca", "parser", "chunk"]
categories = ["parsing"]
exclude = ["/data", "/fuzz"]

[dependencies]
flate2 = { version = "1.1.9", features = ["zlib-rs"], default-features = false }
lz4-java-wrc = "0.2.0"
rayon = { version = "1.11.0", optional = true }
thiserror = "2.0"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
old_mca = { package = "mca", version = "1.1.0", features = ["unsafe"] }
mca-parser = "1.0.2"
simple-anvil = "0.3.3"
anvil-nbt = "0.2.0"
lzma-rust2 = "0.16.2"
na_nbt = { version = "0.2.1", features = ["shared"], default-features = false }

[workspace]
members = ["fuzz"]
resolver = "3"

[profile.release]
opt-level = 3
codegen-units = 1

[features]
default = ["rayon"]
rayon = ["dep:rayon"]

[[bench]]
name = "read"
harness = false

[[bench]]
name = "write"
harness = false
required-features = ["rayon"]

[[bench]]
name = "compare"
harness = false

[[bench]]
name = "get_chunk_data"
harness = false

[[bench]]
name = "write_packed"
harness = false

[[bench]]
name = "custom_compression"
harness = false

[[bench]]
name = "write_single"
harness = false

[[bench]]
name = "into_writer"
harness = false
